import { Injectable } from '@angular/core';
import { Topic } from '../model/topic';

@Injectable({
  providedIn: 'root'
})
export class TopicService {

  private topics = [
    {
      id          : 1,
      name        : "Lifecycle of a frog",
      content     : "<p><span >Frogs of the genus Rana are distributed across all the world's continents, except where the climate is either too dry or too cold. Both the smaller species, such as R. pipiens (the grass frog or leopard frog), and the larger species, such as R. catesbeiana (the bullfrog), are commonly dissected. The position of this last species in the classification of vertebrates may be shown as follows:&nbsp;</span></p> <p><span >Phylum Chordata (animals with a notochord)&nbsp;</span></p> <p><span >Subphylum Vertebrata (animals with a backbone)&nbsp;</span></p> <p><span >Class Amphibia (amphibians)&nbsp;</span></p> <p><span >Order Anura (frogs and toads)&nbsp;</span></p> <p><span >Family Ranidae&nbsp;</span></p> <p><span >Genus Rana&nbsp;</span></p> <p><span >Species Rana catesbeiana</span></p> <p><span >Frogs are amphibians, animals that spend part of their lives under water and the remainder on land. They have long, powerful jumping legs and a very short backbone. Most frogs have teeth (in the upper jaws only) but toads do not have any teeth. Like all amphibians, frogs spend their lives near water because they must return to the water to lay their eggs. Frog eggs are laid in the water. When they hatch into tadpoles, they breathe with gills and swim using a tail. As they mature, they lose their tail, and they develop lungs for breathing air. In harsh climates, frogs bury themselves in sand and mud and hibernate (sleep very deeply) through the cold winter.</span></p> <p><strong>Egg</strong><span > - Tiny frog eggs are laid in masses in the water by a female frog. The eggs hatch into tadpoles.&nbsp;</span></p> <p><strong>Tadpole</strong><span > - (also called the polliwog) this stage hatches from the egg. The tadpole spends its time swimming in the water, eating and growing. Tadpoles breathe using gills and have a tail.</span></p> <p><strong>Tadpole with legs</strong><span > - In this stage the tadpole sprouts legs (and then arms), has a longer body, and has a more distinct head. It still breathes using gills and has a tail.&nbsp;&nbsp;</span></p> <p><strong>Froglet</strong><span > - In this stage, the almost mature frog breathes with lungs and still has some of its tail.&nbsp;</span></p> <p><span ><strong>Adult frog</strong> - The adult frog breathes with lungs and has no tail (it has been absorbed by the body).</span></p>",
      status      : 1,
      image       : "frog-lifecycle.png",
      quiz        : 2
    }
    ,{
      id          : 2,
      name        : "Frog external anatomy",
      content     : "<p><span >Frogs of the genus Rana are distributed across all the world's continents, except where the climate is either too dry or too cold. Both the smaller species, such as R. pipiens (the grass frog or leopard frog), and the larger species, such as R. catesbeiana (the bullfrog), are commonly dissected. The position of this last species in the classification of vertebrates may be shown as follows:&nbsp;</span></p> <p><span >Phylum Chordata (animals with a notochord)&nbsp;</span></p> <p><span >Subphylum Vertebrata (animals with a backbone)&nbsp;</span></p> <p><span >Class Amphibia (amphibians)&nbsp;</span></p> <p><span >Order Anura (frogs and toads)&nbsp;</span></p> <p><span >Family Ranidae&nbsp;</span></p> <p><span >Genus Rana&nbsp;</span></p> <p><span >Species Rana catesbeiana</span></p> <p><span >Frogs are amphibians, animals that spend part of their lives under water and the remainder on land. They have long, powerful jumping legs and a very short backbone. Most frogs have teeth (in the upper jaws only) but toads do not have any teeth. Like all amphibians, frogs spend their lives near water because they must return to the water to lay their eggs. Frog eggs are laid in the water. When they hatch into tadpoles, they breathe with gills and swim using a tail. As they mature, they lose their tail, and they develop lungs for breathing air. In harsh climates, frogs bury themselves in sand and mud and hibernate (sleep very deeply) through the cold winter.</span></p> <p><strong>Egg</strong><span > - Tiny frog eggs are laid in masses in the water by a female frog. The eggs hatch into tadpoles.&nbsp;</span></p> <p><strong>Tadpole</strong><span > - (also called the polliwog) this stage hatches from the egg. The tadpole spends its time swimming in the water, eating and growing. Tadpoles breathe using gills and have a tail.</span></p> <p><strong>Tadpole with legs</strong><span > - In this stage the tadpole sprouts legs (and then arms), has a longer body, and has a more distinct head. It still breathes using gills and has a tail.&nbsp;&nbsp;</span></p> <p><strong>Froglet</strong><span > - In this stage, the almost mature frog breathes with lungs and still has some of its tail.&nbsp;</span></p> <p><span ><strong>Adult frog</strong> - The adult frog breathes with lungs and has no tail (it has been absorbed by the body).</span></p>",
      status      : 1,
      image       : "frog-external-anatomy.jpg",
      quiz        : 5
    }
    ,{
      id          : 3,
      name        : "Frog internal anatomy",
      content     : "<p><span >Frogs of the genus Rana are distributed across all the world's continents, except where the climate is either too dry or too cold. Both the smaller species, such as R. pipiens (the grass frog or leopard frog), and the larger species, such as R. catesbeiana (the bullfrog), are commonly dissected. The position of this last species in the classification of vertebrates may be shown as follows:&nbsp;</span></p> <p><span >Phylum Chordata (animals with a notochord)&nbsp;</span></p> <p><span >Subphylum Vertebrata (animals with a backbone)&nbsp;</span></p> <p><span >Class Amphibia (amphibians)&nbsp;</span></p> <p><span >Order Anura (frogs and toads)&nbsp;</span></p> <p><span >Family Ranidae&nbsp;</span></p> <p><span >Genus Rana&nbsp;</span></p> <p><span >Species Rana catesbeiana</span></p> <p><span >Frogs are amphibians, animals that spend part of their lives under water and the remainder on land. They have long, powerful jumping legs and a very short backbone. Most frogs have teeth (in the upper jaws only) but toads do not have any teeth. Like all amphibians, frogs spend their lives near water because they must return to the water to lay their eggs. Frog eggs are laid in the water. When they hatch into tadpoles, they breathe with gills and swim using a tail. As they mature, they lose their tail, and they develop lungs for breathing air. In harsh climates, frogs bury themselves in sand and mud and hibernate (sleep very deeply) through the cold winter.</span></p> <p><strong>Egg</strong><span > - Tiny frog eggs are laid in masses in the water by a female frog. The eggs hatch into tadpoles.&nbsp;</span></p> <p><strong>Tadpole</strong><span > - (also called the polliwog) this stage hatches from the egg. The tadpole spends its time swimming in the water, eating and growing. Tadpoles breathe using gills and have a tail.</span></p> <p><strong>Tadpole with legs</strong><span > - In this stage the tadpole sprouts legs (and then arms), has a longer body, and has a more distinct head. It still breathes using gills and has a tail.&nbsp;&nbsp;</span></p> <p><strong>Froglet</strong><span > - In this stage, the almost mature frog breathes with lungs and still has some of its tail.&nbsp;</span></p> <p><span ><strong>Adult frog</strong> - The adult frog breathes with lungs and has no tail (it has been absorbed by the body).</span></p>",
      status      : 0,
      image       : "frog-internal-anatomy.jpg",
      quiz        : 2
    }
    ,{
      id          : 4,
      name        : "Determine the sex of the frog",
      content     : "<p><span >Frogs of the genus Rana are distributed across all the world's continents, except where the climate is either too dry or too cold. Both the smaller species, such as R. pipiens (the grass frog or leopard frog), and the larger species, such as R. catesbeiana (the bullfrog), are commonly dissected. The position of this last species in the classification of vertebrates may be shown as follows:&nbsp;</span></p> <p><span >Phylum Chordata (animals with a notochord)&nbsp;</span></p> <p><span >Subphylum Vertebrata (animals with a backbone)&nbsp;</span></p> <p><span >Class Amphibia (amphibians)&nbsp;</span></p> <p><span >Order Anura (frogs and toads)&nbsp;</span></p> <p><span >Family Ranidae&nbsp;</span></p> <p><span >Genus Rana&nbsp;</span></p> <p><span >Species Rana catesbeiana</span></p> <p><span >Frogs are amphibians, animals that spend part of their lives under water and the remainder on land. They have long, powerful jumping legs and a very short backbone. Most frogs have teeth (in the upper jaws only) but toads do not have any teeth. Like all amphibians, frogs spend their lives near water because they must return to the water to lay their eggs. Frog eggs are laid in the water. When they hatch into tadpoles, they breathe with gills and swim using a tail. As they mature, they lose their tail, and they develop lungs for breathing air. In harsh climates, frogs bury themselves in sand and mud and hibernate (sleep very deeply) through the cold winter.</span></p> <p><strong>Egg</strong><span > - Tiny frog eggs are laid in masses in the water by a female frog. The eggs hatch into tadpoles.&nbsp;</span></p> <p><strong>Tadpole</strong><span > - (also called the polliwog) this stage hatches from the egg. The tadpole spends its time swimming in the water, eating and growing. Tadpoles breathe using gills and have a tail.</span></p> <p><strong>Tadpole with legs</strong><span > - In this stage the tadpole sprouts legs (and then arms), has a longer body, and has a more distinct head. It still breathes using gills and has a tail.&nbsp;&nbsp;</span></p> <p><strong>Froglet</strong><span > - In this stage, the almost mature frog breathes with lungs and still has some of its tail.&nbsp;</span></p> <p><span ><strong>Adult frog</strong> - The adult frog breathes with lungs and has no tail (it has been absorbed by the body).</span></p>",
      status      : 0,
      image       : "determine-the-sex-of-the-frog.jpg",
      quiz        : 1
    }
    ,{
      id          : 5,
      name        : "Similarities and distinction of human and frog anatomy",
      content     : "<p><span >Frogs of the genus Rana are distributed across all the world's continents, except where the climate is either too dry or too cold. Both the smaller species, such as R. pipiens (the grass frog or leopard frog), and the larger species, such as R. catesbeiana (the bullfrog), are commonly dissected. The position of this last species in the classification of vertebrates may be shown as follows:&nbsp;</span></p> <p><span >Phylum Chordata (animals with a notochord)&nbsp;</span></p> <p><span >Subphylum Vertebrata (animals with a backbone)&nbsp;</span></p> <p><span >Class Amphibia (amphibians)&nbsp;</span></p> <p><span >Order Anura (frogs and toads)&nbsp;</span></p> <p><span >Family Ranidae&nbsp;</span></p> <p><span >Genus Rana&nbsp;</span></p> <p><span >Species Rana catesbeiana</span></p> <p><span >Frogs are amphibians, animals that spend part of their lives under water and the remainder on land. They have long, powerful jumping legs and a very short backbone. Most frogs have teeth (in the upper jaws only) but toads do not have any teeth. Like all amphibians, frogs spend their lives near water because they must return to the water to lay their eggs. Frog eggs are laid in the water. When they hatch into tadpoles, they breathe with gills and swim using a tail. As they mature, they lose their tail, and they develop lungs for breathing air. In harsh climates, frogs bury themselves in sand and mud and hibernate (sleep very deeply) through the cold winter.</span></p> <p><strong>Egg</strong><span > - Tiny frog eggs are laid in masses in the water by a female frog. The eggs hatch into tadpoles.&nbsp;</span></p> <p><strong>Tadpole</strong><span > - (also called the polliwog) this stage hatches from the egg. The tadpole spends its time swimming in the water, eating and growing. Tadpoles breathe using gills and have a tail.</span></p> <p><strong>Tadpole with legs</strong><span > - In this stage the tadpole sprouts legs (and then arms), has a longer body, and has a more distinct head. It still breathes using gills and has a tail.&nbsp;&nbsp;</span></p> <p><strong>Froglet</strong><span > - In this stage, the almost mature frog breathes with lungs and still has some of its tail.&nbsp;</span></p> <p><span ><strong>Adult frog</strong> - The adult frog breathes with lungs and has no tail (it has been absorbed by the body).</span></p>",
      status      : 0,
      image       : "similarites-distinction.jpg",
      quiz        : 3
    }
  ];

  public getTopics(): Array<Topic> {
    return this.topics;
  }

  public getTopic(topicId: number): Topic {
    return this.topics.find(topic => topic.id == topicId);
  }
}
